#!/bin/bash
wget https://github.com/Damon92/SoftEther/blob/main/softether-vpnserver-v4.37-9758-beta-2021.08.16-linux-x64-64bit.tar.gz
tar -zxvf softether-vpnserver-v4.37-9758-beta-2021.08.16-linux-x64-64bit.tar.gz && cd vpnserver && make && cd /root/ && /root/vpnserver/vpnserver start

ip_addr=ip add show | grep em1 | grep int | awk -F "brd" {'print $1 '} |  awk -F " " {'print $2'}
ip=`echo $ip_addr | awk -F "/" {'print $1'}`
netm=`echo $ip_addr | awk -F "/" {'print $2'}`
gw=`netstat -rn | grep UG |  awk -F " " {'print $2'}`
enp=/etc/sysconfig/network-scripts/ifcfg-em1
sed -i ‘s/dhcp/static/g’ $enp
sed -i ‘/ONBOOT/c ONBOOT=yes’ $enp
cat >> $enp <<EOF
IPADDR=$ip
PREFIX=$netm
EOF
systemctl restart network
route add -host 81.71.50.191/32 gw $gw
route add -net 183.62.127.96/27 gw $gw

